openapi: 3.0.3
info:
  title: 'Kabba API Documentation'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'https://api.kabba.local'
tags:
  -
    name: 'Admin App'
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
paths:
  /api/admin/v1/login:
    post:
      summary: Login
      operationId: login
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Admin App'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'The email address of the user. Must be a valid email address. The <code>email</code> of an existing record in the users table. Must not be greater than 200 characters.'
                  example: rajkc.webdev@gmail.com
                  nullable: false
                password:
                  type: string
                  description: 'The password for the user account. Must not be greater than 50 characters.'
                  example: 'Raj#1234'
                  nullable: false
              required:
                - email
                - password
      security: []
  /api/admin/v1/logout:
    get:
      summary: Logout
      operationId: logout
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'Admin App'
  /api/admin/v1/orders:
    post:
      summary: 'Orders List'
      operationId: ordersList
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Admin App'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  description: 'The status to filter orders. Can be either "All", "Pending", "Paid", "Account", "Partial Refund", "Refunded", or "Failed".'
                  example: Pending
                  nullable: false
                  enum:
                    - All
                    - Pending
                    - Paid
                    - Account
                    - 'Partial Refund'
                    - Refunded
                    - Failed
                per_page:
                  type: integer
                  description: 'The number of items to display per page. Must be at least 1.'
                  example: 10
                  nullable: true
                page:
                  type: integer
                  description: 'The page number for pagination. Must be at least 1.'
                  example: 1
                  nullable: true
              required:
                - status
