<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Classifies task comments so Waiting reasons and Help Needed requests
 * generated by the status workflow can be rendered with a subtle origin
 * badge in the normal comment stream. Nullable — every existing comment
 * stays an ordinary (untyped) comment.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('daily_task_comments', function (Blueprint $table) {
            $table->string('comment_type')->nullable()->after('comment');
        });
    }

    public function down(): void
    {
        Schema::table('daily_task_comments', function (Blueprint $table) {
            $table->dropColumn('comment_type');
        });
    }
};
