<?php

namespace App\Enums\Tasks;

/**
 * Classifies a task comment by its origin. Ordinary comments carry no type
 * (null) and stay ordinary; contextual comments are generated by the status
 * workflow so the human explanation lives in the conversation, not stranded
 * in the audit log.
 */
enum TaskCommentType: string
{
    case Standard   = 'standard';
    case Waiting    = 'waiting';
    case HelpNeeded = 'help_needed';
    case Status     = 'status';

    public function label(): string
    {
        return match ($this) {
            self::Standard   => 'Comment',
            self::Waiting    => 'Waiting',
            self::HelpNeeded => 'Help Needed',
            self::Status     => 'Status',
        };
    }

    /** Tailwind badge classes — mirror the matching TaskStatus colors. */
    public function badgeClasses(): string
    {
        return match ($this) {
            self::Waiting    => 'bg-orange-100 text-orange-700',
            self::HelpNeeded => 'bg-purple-100 text-purple-700',
            default          => 'bg-gray-100 text-gray-600',
        };
    }

    /** A contextual comment carries a visible origin badge; Standard does not. */
    public function isContextual(): bool
    {
        return $this !== self::Standard;
    }
}
